# Global Application Configuration
spring:
  application:
    name: ProjectHub
  
  # Database Configuration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Migration Configuration  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Security Configuration
  security:
    user:
      name: ${APP_USER_NAME:admin}
      password: ${APP_USER_PASSWORD:password}

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 2.0

  cloud:
    gateway:
      routes:
        - id: skills_service
          uri: lb://skills-service
          predicates:
            - Path=/api/skills/**
        - id: learning_service
          uri: lb://learning-service
          predicates:
            - Path=/api/learning/**

# Application Specific Configuration
app:
  # CORS Configuration
  cors:
    allowed-origins: http://localhost:4200
  
  # Security Configuration  
  security:
    token:
      access-token-validity-minutes: 30
      refresh-token-validity-days: 7
      max-active-tokens: 5
      token-rotation-grace-period-seconds: 30

  # File Storage Configuration
  storage:
    location: ${user.home}/projecthub/uploads
    max-file-size: 10MB

# Sync Configuration (Desktop Profile)
sync:
  remote:
    url: jdbc:postgresql://localhost:5432/projecthub
    username: ${SYNC_USER}
    password: ${SYNC_PASSWORD}
  local:
    path: ./data/local/projecthub
  network:
    timeout: 5000

# Logging Configuration
logging:
  level:
    root: INFO
    com.projecthub: DEBUG
    com.projecthub.base.student: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
      group:
        student:
          include: studentModuleHealth
  metrics:
    tags:
      application: ${spring.application.name}
    enable:
      student: true
    distribution:
      percentiles-histogram:
        student.operation.timing: true
        student.query.timing: true
      sla:
        student.operation.timing: 100ms,500ms,1s
        student.query.timing: 50ms,200ms,500ms

# Documentation Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

rabbitmq:
  host: localhost
  port: 5672
  username: ${RABBITMQ_USERNAME:admin}
  password: ${RABBITMQ_PASSWORD:admin123}
  management:
    port: 15672
    ssl:
      enabled: true
    server:
      port: 15672
      address: 127.0.0.1  # Localhost only

webauthn:
  rp:
    id: localhost
    name: ProjectHub
    origin: http://localhost:8080
  timeout: 60000
  authenticator:
    attachment: cross-platform
    user-verification: preferred
    resident-key: preferred

# Apache Fortress Configuration
projecthub:
  auth:
    fortress:
      bootstrap: true
      admin:
        username: admin
        password: admin123

# LDAP Server Configuration
ldap:
  server:
    host: localhost
    port: 10389
    admin-dn: uid=admin,ou=system
    admin-password: secret
  connection-pool:
    min: 1
    max: 10
    validate: true

# Fortress Application Configuration
fortress:
  enable:
    audit: true
    resource-check: true
  session:
    timeout: 3600  # seconds