version: '3'

services:
  apacheds:
    image: openmicroscopy/apacheds:2.0.0
    container_name: projecthub-apacheds
    ports:
      - "10389:10389"  # LDAP port
      - "10636:10636"  # LDAPS port
    environment:
      - APACHEDS_INSTANCE=default
      - APACHEDS_PARTITION=projecthub
      - APACHEDS_ADMIN_USER=uid=admin,ou=system
      - APACHEDS_ADMIN_PASSWORD=secret
    volumes:
      - ldap-data:/var/lib/apacheds-2.0.0/default
    networks:
      - projecthub-network
    restart: unless-stopped

networks:
  projecthub-network:
    driver: bridge

volumes:
  ldap-data: