server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: projecthub-gateway
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
        - AddResponseHeader=X-Gateway-Version, 1.0.0
        - AddRequestHeader=X-Request-Timestamp, ${now:yyyy-MM-dd HH:mm:ss}
        - name: Retry
          args:
            retries: 3
            methods: GET
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

# Import shared security configuration
projecthub:
  security:
    jwt:
      issuer: projecthub
    cors:
      allowed-origins:
        - http://localhost:4200
        - http://localhost:8080
        - https://*.projecthub.com
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
    headers:
      Content-Security-Policy: "default-src 'self'"
      X-Content-Type-Options: nosniff
      X-XSS-Protection: "1; mode=block"
      X-Frame-Options: DENY
  auth:
    fortress:
      enabled: true
      bootstrap: false
      config-file: fortress.properties

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: when_authorized
    gateway:
      enabled: true
  info:
    git:
      mode: full

logging:
  level:
    com.projecthub.gateway: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
    org.apache.directory.fortress: INFO
    reactor.netty: INFO