app:
  components:
    filepath: classpath:data/components.csv
  projects:
    filepath: classpath:data/projects.csv
  schools:
    filepath: classpath:data/schools.csv
  students:
    filepath: classpath:data/students.csv
  submissions:
    filepath: classpath:data/submissions.csv
    tempdir: classpath:data/tempdir
  tasks:
    filepath: classpath:data/tasks.csv
  teachers:
    filepath: classpath:data/teachers.csv
  teams:
    filepath: classpath:data/teams.csv
  cohorts:
    filepath: classpath:data/cohorts.csv

spring:
  profiles:
    active: jpa # Change to 'csv' to use CSV implementation
