/*
 * This source file was generated by the Gradle 'init' task
 */
package projecthub.csv.plugin;

import org.junit.jupiter.api.Test;

class AppTest {
    AppTest() {
    }

    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
